### ISSUE TITLE
Nothing happens when i run the dojo binary in Ubuntu on WSL2

### ISSUE THREAD

**Issue by syedatifakhtar** [kudulab/dojo#19]
Installed dojo on Ubuntu in WSL2 using brew

``` brew install kudulab/homebrew-dojo-osx/dojo```

Trying to build gocd which has a dojofile using

```
➜  gocd git:(master) dojo 
➜  gocd git:(master) 
```

Its the same when uninstalled and installed using manual steps

```
➜  gocd git:(master) brew uninstall dojo
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/dojo/0.9.0... (3 files, 2.7MB)
➜ desktop-workspace wget -O /tmp/dojo https://github.com/kudulab/dojo/releases/download/0.9.0/dojo_linux_amd64
...
➜  desktop-workspace sudo chmod +x /tmp/dojo
➜  desktop-workspace sudo mv /tmp/dojo /usr/bin/dojo
➜  z ~/desktop-workspace/gocd
➜  gocd git:(master) dojo
➜  gocd git:(master) dojo
```

Docker is being run using the Docker Desktop WSL 2 backend (https://docs.docker.com/docker-for-windows/wsl/)

```
➜  gocd git:(master) docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

➜  gocd git:(master) docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by tomzo** [comment]
Hi @syedatifakhtar 

Thank you for sharing the issue. I'm not familiar with WSL2 and the current state of docker in Windows. In general, Dojo is not tested on windows stacks at the moment.

Second problem might be usage of brew on Linux systems. This is again, another case that we didn't intend to support. brew feed was added together with Mac support. On Linux, atm, we would expect users to just download the binary.

Can you also please paste the output of `dojo -version` just to confirm that binary is executing at all?

**Comment by xmik** [comment]
Hello,

I did a smoke test and successfully installed Dojo 0.11.0 on WSL2 using [manual steps](https://github.com/kudulab/dojo#installation). This Dojofile was used:
```
DOJO_DOCKER_IMAGE=kudulab/terraform-dojo:1.6.0
```
and I run
* Dojo interactively with `dojo` and then `terraform -version` 
* Dojo not interactively with `dojo 'terraform -version'`

It worked without problems. 
Docker version was 20.10.12, Bash version 5.0.17(1)-release.

I'm going to close this issue, but feel free to reopen.
